### ISSUE TITLE
Spring Kerberos on IBM JVM

### ISSUE THREAD

**Issue by Lucasvo1** [spring-projects/spring-security-kerberos#104]
We are trying to implement Spring Kerberos in Tomcat on RHEL using the IBM JVM. I have taken the code for the IBM specific parts from https://jira.spring.io/browse/SES-15 

The problem is that I have been getting the same error for the last two days:

     Caused by: org.ietf.jgss.GSSException: org.ietf.jgss.GSSException, major code: 10, minor code: 0
        major string: Defective token
        minor string: Bad token tag: 78
        at com.ibm.security.jgss.i18n.I18NException.throwGSSException(I18NException.java:31) ~[na:8.0 build_20161128]
        at com.ibm.security.jgss.TokenHeader.a(TokenHeader.java:157) ~[na:8.0 build_20161128]
        at com.ibm.security.jgss.TokenHeader.a(TokenHeader.java:117) ~[na:8.0 build_20161128]
        at com.ibm.security.jgss.TokenHeader.<init>(TokenHeader.java:79) ~[na:8.0 build_20161128]
        at com.ibm.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:480) ~[na:8.0 build_20161128]
        at com.ibm.security.jgss.GSSContextImpl.acceptSecContext(GSSContextImpl.java:398) ~[na:8.0 build_20161128]
        at com.lgt.toolbox.config.security.kerberos.IbmJaasKerberosTicketValidator$KerberosValidateAction.run(IbmJaasKerberosTicketValidator.java:129) ~[classes/:na]
        at com.lgt.toolbox.config.security.kerberos.IbmJaasKerberosTicketValidator$KerberosValidateAction.run(IbmJaasKerberosTicketValidator.java:111) ~[classes/:na]
        at java.security.AccessController.doPrivileged(AccessController.java:686) ~[na:1.8.0]
        ... 53 common frames omitted

This is the log when the application starts: 

      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: debug=true
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: principal=user/server@REALM
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: credsType=accept only
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 config: useDefaultCcache=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 config: useCcache=null
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 config: useDefaultKeytab=false
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 config: useKeytab=krb_toolbox_rc4.keytab
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: forwardable=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: renewable=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: proxiable=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: tryFirstPass=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: useFirstPass=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: moduleBanner=false (default)
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 JAAS config: interactive login? no
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 Try keytab for principal=user/server@REALM
      [JGSS_DBG_CRED]  http-nio-8443-exec-27 No Kerberos creds in keytab for principal user/server@REALM
     [JGSS_DBG_CRED]  http-nio-8443-exec-27 Login successful
     [JGSS_DBG_CRED]  http-nio-8443-exec-27 kprincipal : user/server@REALM
     [JGSS_DBG_CRED]  http-nio-8443-exec-27 KeyTab added to Subject
     [JGSS_DBG_CRED]  http-nio-8443-exec-27 No keys to add to Subject for user/server@REALM

Does anyone know in which area I should be looking to fix this? 

Edit: Just for sake of completeness, there was a problem with the JCE Policy files. As our KDC gives out AES256 tickets, they could not be used by the client. By replacing the newest IBM JCE Policy files, everything works as expected.

**Comment by thorveshubham** [comment]
@Hehohehoheho 
When you say replacing IBM JCE Policy files fixed this issue, what exactly di you replace ?
