### ISSUE TITLE
Executing KerberosRestTemplate runs into "Unable to obtain password from user" error

### ISSUE THREAD

**Issue by ruchidalal** [spring-projects/spring-security-kerberos#106]
I have setup the Kerberos environment as per the setup steps in the document here : [http://docs.spring.io/spring-security-kerberos/docs/1.0.2.BUILD-SNAPSHOT/reference/htmlsingle/#browserspnegoconfig]

I was able to run the spnego-form-auth samples. However on trying to run the rest example I run into this error -
Caused by: org.springframework.web.client.RestClientException: Error running rest call; nested exception is javax.security.auth.login.LoginException: Unable to obtain password from user

        at org.springframework.security.kerberos.client.KerberosRestTemplate.doExecute(KerberosRestTemplate.java:196)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:237)
        at demo.app.Application.run(Application.java:28)
        at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:677)
        ... 10 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain password from user

        at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:897)
        at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760)
        at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)

Could you help me with it or let me know the exact steps of running the rest service example

**Comment by jomach** [comment]
same problem here

**Comment by ruchidalal** [comment]
@jomach : Did you find a resolution this problem?

**Comment by jomach** [comment]
I have activated the debug for that modules and I see a PBX... expection. No idea what it is.

**Comment by courteous** [comment]
jomach can post how did you activated the debug. I have not found a solution yet. In case you have could you share it please.

**Comment by jomach** [comment]
-Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true
 and KRB5_TRACE=/dev/stdout

**Comment by jomach** [comment]
@courteous @ruchidalal: I had the same issue. This works fine. Check that you have -Djava.security.krb5.conf=/etc/krb5.conf and that the DEFAULT domain on the config matches what you need.
