### ISSUE TITLE
Getting error when using keytab-file for spnego

### ISSUE THREAD

**Issue by ivanfomkin** [spring-projects/spring-security-kerberos#174]
I'm try to implements domain auth in my app.
I run sec-server-spnego-form-auth with my keytab-file
I'm using principal: `HTTP/my-test@DOMAIN.LOCAL` (this principal contains in keytab)
But when i try get secured endpoint (`http://localhost:8080/hello`) i get response with 500 status. In logs i found this:
```
org.springframework.security.authentication.BadCredentialsException: GSSContext name of the context initiator is null
```
But when I pass my login and password in login page (`http://localhost:8080/login`) and get secured endpoint again (`http://localhost:8080/hello`) it works fine and i get current user info
It's bug? Or my config is wrong?

**Comment by venkatnaveen7** [comment]
Could you please enable the trace logs and see for which request this error has been thrown?
is KRB token passed from client ..?you can verify the token list by running command klist

**Comment by venkatnaveen7** [comment]
Well
I tried this my local PC and I'm also getting the same error

 Checking authorization on SecurityContextHolderAwareRequestWrapper[ org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequest@22d612ea] using org.springframework.security.authorization.AuthenticatedAuthorizationManager@26cbd034
2023-05-02T15:04:52.825+04:00 TRACE 428404 --- [nio-8090-exec-5] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.38.50.218, SessionId=D0FE6DDXXXSDDEE86D1D3A27D3F275FDA27205], Granted Authorities=[ROLE_ANONYMOUS]]
2023-05-02T15:04:52.826+04:00 TRACE 428404 --- [nio-8090-exec-5] o.s.s.w.a.ExceptionTranslationFilter     : Sending AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.38.50.218, SessionId=D0FE6DDXXXSDDEE86D1D3A27D3F275FDA27205], Granted Authorities=[ROLE_ANONYMOUS]] to authentication entry point since access is denied

org.springframework.security.access.AccessDeniedException: Access Denied
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.0.1.jar!/:6.0.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar!/:6.0.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.0.1.jar!/:6.0.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.0.1.jar!/:6.0.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:3

**Comment by venkatnaveen7** [comment]
But we could see Authenticated=true   Seems its part of Authorization

**Comment by ivanfomkin** [comment]
> The SPN has to match the FQDN of your web server, e.g. `HTTP/server.example.com@EXAMPLE.COM` if your server is available at `server.example.com` for your clients. Port numbers are not relevant.
> 
> That said, Kerberos will never work when testing against a web server at `localhost`.

Hmm...
Does creating row in hosts file solve my problem?
127.0.0.1 my-test

Or I must testing kerberos integration in other machine?

Now I try to edit my hosts file and I get 404 for any secured endpoint (My user does not authenticate)

**Comment by venkatnaveen7** [comment]
We are getting this in only in TRACE log    ,disabling TRACE log will not show this error

2023-05-02T15:04:52.825+04:00 TRACE 428404 --- [nio-8090-exec-5] o.s.s.w.a.AnonymousAuthenticationFilter : Set SecurityContextHolder to AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.38.50.218, SessionId=D0FE6DDXXXSDDEE86D1D3A27D3F275FDA27205], Granted Authorities=[ROLE_ANONYMOUS]]
2023-05-02T15:04:52.826+04:00 TRACE 428404 --- [nio-8090-exec-5] o.s.s.w.a.ExceptionTranslationFilter : Sending AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.38.50.218, SessionId=D0FE6DDXXXSDDEE86D1D3A27D3F275FDA27205], Granted Authorities=[ROLE_ANONYMOUS]] to authentication entry point since access is denied

**Comment by ivanfomkin** [comment]
> Now I try to edit my hosts file and I get 404 for any secured endpoint (My user does not authenticate)

Solved. I try to use spring security kerberos in my app without provide login form.
My solution:
1. Copy login form (`login.html` from example)
2. Add LoginFormController with get mapping (`/login`) and return `login.html` template

Now it's work fine!

**Comment by venkatnaveen7** [comment]
[ivanfomkin](https://github.com/ivanfomkin)  Its the same as the solution which you mentioned in your 1st question
I believe if we use spring security kerberos there no separate authentication required from the user as spring security kerberos should pick the login from the current logged-in user.
Also to skip the User account verification with AD from local PC you may refer to this example
https://seenukarthi.com/security/2014/08/13/localhost-authentication-spring-kerberos/
